export const powerOnSteps = [
  { title: '检查电源', desc: '确认车间电源电压符合机床要求 (通常为三相380V)' },
  { title: '检查气源', desc: '确认压缩空气压力在 0.5~0.7 MPa' },
  { title: '检查冷却液', desc: '冷却液液位是否正常，浓度是否合适', warning: '冷却液不足会影响加工质量' },
  { title: '检查润滑油', desc: '检查各润滑部位油位是否正常' },
  { title: '机床通电', desc: '打开机床主电源，等待系统自检完成' },
  { title: '手动复位', desc: '执行机床回零操作 (各轴回参考点)', warning: '确保工作台上无障碍物' },
  { title: '预热空运行', desc: '空运行10~15分钟，使机床达到热平衡' },
  { title: '确认刀具状态', desc: '检查刀具磨损情况，必要时更换' },
  { title: '装夹工件', desc: '正确装夹工件，确认定位和夹紧可靠', warning: '确认工件装夹牢固' },
  { title: '试切验证', desc: '执行首件试切，验证尺寸精度' },
]

export const powerOffSteps = [
  { title: '完成当前程序', desc: '等待当前加工程序完全执行完毕' },
  { title: '退回安全位置', desc: '将各轴移动到安全位置，主轴停止' },
  { title: '清理切屑', desc: '清理工作台上的切屑和杂物' },
  { title: '释放工件', desc: '松开夹具，取下工件' },
  { title: '清洁机床', desc: '擦拭机床外表面，保持清洁' },
  { title: '关闭冷却液', desc: '关闭冷却液系统' },
  { title: '关闭电源', desc: '关闭控制系统电源', warning: '请勿直接关闭总电源' },
  { title: '关闭总电源', desc: '关闭机床主电源' },
  { title: '记录日志', desc: '记录当日机床运行状态和异常情况' },
]

export const emergencyProcedures = [
  {
    icon: '🛑',
    title: '紧急停机',
    level: 'danger',
    label: '严重',
    color: '#ef4444',
    steps: ['立即按下红色急停按钮', '切断各轴运动', '主轴停止', '冷却液关闭', '评估现场安全后再处理'],
    prevention: '定期检查急停按钮功能，保持通道畅通无阻。',
  },
  {
    icon: '🔧',
    title: '刀具断裂',
    level: 'warning',
    label: '警告',
    color: '#f59e0b',
    steps: ['按进给保持键暂停加工', '记录当前程序段号', '缓慢退刀至安全位置', '更换刀具', '重新对刀', '从暂停位置继续加工'],
    prevention: '定期检查刀具磨损，使用合适的切削参数。',
  },
  {
    icon: '⚠️',
    title: '工件松动',
    level: 'warning',
    label: '警告',
    color: '#f59e0b',
    steps: ['立即暂停加工', '退回安全位置', '重新装夹找正', '重新对刀', '从程序起始位置重新加工'],
    prevention: '装夹工件时确保夹紧力足够，使用合适的夹具。',
  },
  {
    icon: '🔥',
    title: '主轴过载',
    level: 'danger',
    label: '严重',
    color: '#ef4444',
    steps: ['立即降低进给速度', '检查刀具磨损', '检查切削参数是否过大', '必要时更换刀具'],
    prevention: '合理选择切削参数，定期检查主轴状态。',
  },
  {
    icon: '💥',
    title: '碰撞发生',
    level: 'danger',
    label: '严重',
    color: '#ef4444',
    steps: ['立即按急停', '检查刀具损坏情况', '检查工件损坏情况', '检查机床精度', '确定原因后恢复'],
    prevention: '加工前进行模拟验证，确认刀具路径无干涉。',
  },
  {
    icon: '❌',
    title: '程序错误',
    level: 'info',
    label: '提示',
    color: '#3b82f6',
    steps: ['程序暂停', '定位到出错位置', '检查并修改程序', '重新验证后执行'],
    prevention: '编程后仔细检查程序，使用模拟软件验证。',
  },
]

export const maintenanceItems = [
  { level: 'daily', title: '清理工作台和导轨切屑', description: '使用毛刷和吸尘器清理工作台和导轨上的切屑，保持导轨面清洁。', tips: ['使用软毛刷', '避免切屑进入导轨间隙'] },
  { level: 'daily', title: '检查冷却液浓度', description: '使用折光仪或浓度计检查冷却液浓度，保持在推荐范围内。', tips: ['浓度过高影响散热', '浓度过低易滋生细菌'] },
  { level: 'daily', title: '检查各轴润滑', description: '检查X、Y、Z轴润滑油位，确保润滑系统正常工作。', tips: ['润滑油不足会加速磨损', '注意观察润滑泵工作状态'] },
  { level: 'daily', title: '检查气压', description: '检查压缩空气压力，确保在0.5~0.7MPa范围内。', tips: ['气压不足影响换刀', '注意过滤水分'] },
  { level: 'daily', title: '擦拭机床外观', description: '使用干净布擦拭机床外表面，保持设备整洁。', tips: ['避免使用有机溶剂', '检查是否有锈蚀'] },
  { level: 'weekly', title: '清洁或更换冷却液过滤网', description: '清理冷却液过滤网中的杂质，必要时更换过滤网。', tips: ['避免堵塞影响冷却', '定期检查过滤效果'] },
  { level: 'weekly', title: '检查主轴润滑', description: '检查主轴润滑油位和润滑状态，确保主轴正常运转。', tips: ['注意主轴温度', '监听主轴运转声音'] },
  { level: 'weekly', title: '检查刀具库清洁', description: '清理刀具库中的切屑和灰尘，检查刀具夹紧机构。', tips: ['保持刀库整洁', '检查刀具定位精度'] },
  { level: 'weekly', title: '检查导轨润滑装置', description: '检查导轨润滑装置的工作状态，确保润滑油均匀覆盖。', tips: ['检查油路是否畅通', '注意润滑油量'] },
  { level: 'monthly', title: '更换冷却液', description: '完全更换冷却液，清洗冷却液箱和管路。', tips: ['清洗滤网', '检测水质'] },
  { level: 'monthly', title: '检查液压系统压力', description: '检查液压系统压力是否正常，检查液压油位。', tips: ['压力异常需检查', '注意液压油温度'] },
  { level: 'monthly', title: '检查主轴精度', description: '使用千分表检测主轴跳动和端面精度。', tips: ['精度超差需维修', '记录检测数据'] },
  { level: 'monthly', title: '校准各轴精度', description: '使用激光干涉仪校准各轴定位精度和重复定位精度。', tips: ['环境温度要求恒定', '记录校准结果'] },
  { level: 'monthly', title: '清洁控制面板', description: '清洁控制面板上的灰尘和污渍，检查按键灵敏度。', tips: ['使用软布擦拭', '避免液体进入'] },
  { level: 'quarterly', title: '检查并更换润滑油', description: '检查各部位润滑油状态，必要时更换。', tips: ['参考使用手册', '注意油品兼容性'] },
  { level: 'quarterly', title: '检查传动皮带张紧', description: '检查主轴皮带和各轴传动皮带的张紧度。', tips: ['张紧力要适当', '检查皮带磨损情况'] },
  { level: 'quarterly', title: '清洁光栅尺', description: '清洁光栅尺的光学尺面，确保测量精度。', tips: ['使用酒精棉签', '避免划伤尺面'] },
  { level: 'quarterly', title: '检查编码器状态', description: '检查各轴编码器工作状态，确认位置反馈正常。', tips: ['检查编码器连线', '测试原点复归精度'] },
  { level: 'quarterly', title: '备份机床参数', description: '备份机床所有参数和加工程序，防止数据丢失。', tips: ['使用U盘或网络', '验证备份完整性'] },
  { level: 'yearly', title: '全面精度校准', description: '对机床进行全面的几何精度和定位精度校准。', tips: ['请专业人员进行', '校准后记录存档'] },
  { level: 'yearly', title: '更换液压油', description: '完全更换液压系统的液压油，清洗液压油箱。', tips: ['使用推荐型号', '检查油液污染度'] },
  { level: 'yearly', title: '检查滚珠丝杠预紧', description: '检查各轴滚珠丝杠的预紧力，必要时调整。', tips: ['预紧力过大增加负载', '预紧力过小影响精度'] },
  { level: 'yearly', title: '更换主轴轴承', description: '检查主轴轴承状态，必要时更换。', tips: ['由专业人员操作', '更换后需重新校准'] },
  { level: 'yearly', title: '系统升级检查', description: '检查数控系统软件版本，必要时升级。', tips: ['升级前备份', '升级后测试验证'] },
]

export const alarmSystems = ['FANUC', 'Siemens', '华中', '凯恩帝', 'Haas']

export const alarmCodes = [
  { code: 'E01', system: 'FANUC', category: '主轴', message: '主轴驱动过载', cause: '切削参数过大或主轴故障', solution: '降低切削参数或检查主轴', level: '危险' },
  { code: 'E02', system: 'FANUC', category: '伺服', message: '伺服驱动报警', cause: '伺服电机故障或电源异常', solution: '检查伺服电机和驱动电源', level: '危险' },
  { code: 'E03', system: 'FANUC', category: '主轴', message: '主轴过热保护', cause: '冷却系统故障或转速过高', solution: '检查冷却系统，降低转速', level: '危险' },
  { code: 'E04', system: 'FANUC', category: '参数', message: 'X轴超出限位', cause: '程序错误或原点丢失', solution: '手动将X轴移动到安全位置', level: '危险' },
  { code: 'E05', system: 'FANUC', category: '参数', message: 'Y轴超出限位', cause: '程序错误或原点丢失', solution: '手动将Y轴移动到安全位置', level: '危险' },
  { code: 'E06', system: 'FANUC', category: '参数', message: 'Z轴超出限位', cause: '程序错误或原点丢失', solution: '手动将Z轴移动到安全位置', level: '危险' },
  { code: 'W01', system: 'FANUC', category: '冷却液', message: '冷却液液位过低', cause: '冷却液消耗过快或泄漏', solution: '添加冷却液', level: '警告' },
  { code: 'W02', system: 'FANUC', category: '气压', message: '润滑油不足', cause: '润滑系统故障', solution: '添加润滑油', level: '警告' },
  { code: 'W03', system: 'FANUC', category: '气压', message: '气压过低', cause: '气源压力不足或管路泄漏', solution: '检查气源和管路', level: '警告' },
  { code: 'W04', system: 'FANUC', category: '刀具', message: '刀具寿命到期', cause: '刀具已达设定寿命', solution: '更换刀具或延长寿命设置', level: '警告' },
  { code: 'W05', system: 'FANUC', category: '参数', message: '工件计数完成', cause: '已加工工件达到设定数量', solution: '执行相应操作后清零', level: '提示' },
  { code: 'I01', system: 'FANUC', category: '通讯', message: '程序执行完成', cause: '程序正常结束', solution: '正常，开始下一个循环', level: '提示' },
  { code: 'I02', system: 'FANUC', category: '刀库', message: '刀具库位置异常', cause: '刀库定位错误', solution: '手动复位刀具库', level: '提示' },

  { code: '25001', system: 'Siemens', category: '伺服', message: '伺服轴跟随误差超限', cause: '轴负载过大或编码器故障', solution: '检查轴负载和编码器', level: '危险' },
  { code: '25002', system: 'Siemens', category: '主轴', message: '主轴驱动故障', cause: '主轴过流或驱动损坏', solution: '检查主轴驱动模块', level: '危险' },
  { code: '25003', system: 'Siemens', category: '电源', message: '电源模块故障', cause: '电源电压异常', solution: '检查电源模块和供电', level: '危险' },
  { code: '25004', system: 'Siemens', category: '主轴', message: '主轴过热', cause: '冷却系统故障', solution: '检查冷却系统，停机降温', level: '警告' },
  { code: '25005', system: 'Siemens', category: '参数', message: '轴软件限位报警', cause: '轴运动超出软件限位', solution: '修改程序或调整限位', level: '警告' },

  { code: 'E101', system: '华中', category: '伺服', message: '伺服驱动过流', cause: '电机过载或短路', solution: '检查电机和驱动器', level: '危险' },
  { code: 'E102', system: '华中', category: '主轴', message: '主轴变频器报警', cause: '变频器故障或过载', solution: '检查主轴变频器', level: '危险' },
  { code: 'E103', system: '华中', category: '电源', message: '系统电源异常', cause: '电源模块故障', solution: '检查电源模块', level: '危险' },
  { code: 'W101', system: '华中', category: '冷却液', message: '冷却液液位过低', cause: '冷却液消耗过快', solution: '添加冷却液', level: '警告' },
  { code: 'W102', system: '华中', category: '刀库', message: '刀库定位不准', cause: '刀库机械故障', solution: '检查刀库机械结构', level: '警告' },

  { code: 'E201', system: '凯恩帝', category: '伺服', message: '伺服驱动器报警', cause: '伺服电机故障', solution: '检查伺服电机和驱动', level: '危险' },
  { code: 'E202', system: '凯恩帝', category: '主轴', message: '主轴变频器故障', cause: '变频器过流或过压', solution: '检查主轴变频器', level: '危险' },
  { code: 'W201', system: '凯恩帝', category: '气压', message: '气压不足', cause: '气源压力低', solution: '调整气源压力', level: '警告' },
  { code: 'W202', system: '凯恩帝', category: '冷却液', message: '冷却液不足', cause: '冷却液消耗', solution: '添加冷却液', level: '警告' },

  { code: 'E301', system: 'Haas', category: '伺服', message: 'Servo drive fault', cause: '伺服驱动故障', solution: '检查伺服驱动模块', level: '危险' },
  { code: 'E302', system: 'Haas', category: '主轴', message: 'Spindle over temperature', cause: '主轴过热', solution: '停机冷却，检查润滑', level: '危险' },
  { code: 'E303', system: 'Haas', category: '电源', message: 'Power supply fault', cause: '电源模块故障', solution: '检查电源模块', level: '危险' },
  { code: 'W301', system: 'Haas', category: '冷却液', message: 'Coolant level low', cause: '冷却液不足', solution: '添加冷却液', level: '警告' },
  { code: 'W302', system: 'Haas', category: '刀具', message: 'Tool life exceeded', cause: '刀具寿命到期', solution: '更换刀具', level: '警告' },
]
