export const controllers = [
  {
    id: 'fanuc',
    name: 'FANUC 法兰克',
    country: '日本',
    logo: '🟦',
    features: {
      fullName: 'FANUC Corporation',
      marketShare: '全球第一',
      reliability: '极高',
      programmingEase: '简单',
      commonModels: ['FANUC 0i-MF', 'FANUC 0i-TF', 'FANUC 31i-A5'],
    },
    codeDifferences: {
      coordinates: 'G90 绝对 / G91 增量',
      feedRate: 'F100 (mm/min) 或 F0.1 (mm/r)',
      toolChange: 'M6 T代码',
      spindle: 'S1000 M3',
      coolant: 'M8 开 / M9 关',
    },
    postProcessor: {
      code: 'FANUC_0i',
      fileFormat: '.NC',
      encoding: 'ANSI',
      lineNumber: '自动生成',
      specialChars: '支持',
    },
    tips: ['G54-G59 工件坐标系选择', 'G43 刀具长度补偿', 'G41/G42 刀具半径补偿', 'M98 子程序调用', '支持宏程序编程'],
  },
  {
    id: 'siemens',
    name: 'Siemens 西门子',
    country: '德国',
    logo: '🟢',
    features: {
      fullName: 'Siemens AG',
      marketShare: '欧洲领先',
      reliability: '高',
      programmingEase: '中等',
      commonModels: ['Sinumerik 840D', 'Sinumerik 828D', 'Sinumerik 808D'],
    },
    codeDifferences: {
      coordinates: 'G90 绝对 / G91 增量',
      feedRate: 'F100 (mm/min) 或 F0.1 (mm/r)',
      toolChange: 'M6 T代码',
      spindle: 'S1000 M3',
      coolant: 'M7/M8 开 / M9 关',
    },
    postProcessor: {
      code: 'SIEMENS_840D',
      fileFormat: '.MPF',
      encoding: 'ANSI/UTF-8',
      lineNumber: '可选',
      specialChars: '支持',
    },
    tips: ['TRAFO 坐标转换功能', 'FRAMES 坐标平移旋转', 'CYCLE 固定循环功能', '支持高级语言扩展', 'ShopMill/ShopTurn 向导编程'],
  },
  {
    id: 'heidenhain',
    name: 'Heidenhain 海德汉',
    country: '德国',
    logo: '🔵',
    features: {
      fullName: 'Dr. Johannes Heidenhain GmbH',
      marketShare: '高端领域',
      reliability: '极高',
      programmingEase: '较简单',
      commonModels: ['TNC 640', 'TNC 320', 'TNC 128'],
    },
    codeDifferences: {
      coordinates: '绝对/增量通过 G90/G91 切换',
      feedRate: 'F100 (mm/min)',
      toolChange: 'TOOL CALL',
      spindle: 'S1000 M3',
      coolant: 'M8 开 / M9 关',
    },
    postProcessor: {
      code: 'HEIDENHAIN_TNC640',
      fileFormat: '.H',
      encoding: 'ANSI',
      lineNumber: '自动生成',
      specialChars: '支持',
    },
    tips: [' conversational 对话式编程', '支持循环编程', 'TOOL CALL 刀具调用', 'PLANE 功能坐标系旋转', '支持 5 轴加工'],
  },
  {
    id: 'huazhong',
    name: '华中数控',
    country: '中国',
    logo: '🟨',
    features: {
      fullName: '武汉华中数控股份有限公司',
      marketShare: '国内领先',
      reliability: '中等',
      programmingEase: '简单',
      commonModels: ['HNC-8', 'HNC-210', 'HNC-18xp'],
    },
    codeDifferences: {
      coordinates: 'G90 绝对 / G91 增量',
      feedRate: 'F100 (mm/min)',
      toolChange: 'M6 T代码',
      spindle: 'S1000 M3',
      coolant: 'M8 开 / M9 关',
    },
    postProcessor: {
      code: 'HUAZHONG_HNC8',
      fileFormat: '.TXT',
      encoding: 'ANSI',
      lineNumber: '自动生成',
      specialChars: '有限支持',
    },
    tips: ['与 FANUC 代码兼容', '支持国产 CAM 软件后处理', '中文界面操作方便', '价格优势明显', '售后服务好'],
  },
  {
    id: 'knd',
    name: 'KND 凯恩帝',
    country: '中国',
    logo: '🔴',
    features: {
      fullName: '北京凯恩帝数控技术有限责任公司',
      marketShare: '国内前列',
      reliability: '中等',
      programmingEase: '简单',
      commonModels: ['KND K100', 'KND K200', 'KND K300'],
    },
    codeDifferences: {
      coordinates: 'G90 绝对 / G91 增量',
      feedRate: 'F100 (mm/min)',
      toolChange: 'M6 T代码',
      spindle: 'S1000 M3',
      coolant: 'M8 开 / M9 关',
    },
    postProcessor: {
      code: 'KND_K200',
      fileFormat: '.TXT',
      encoding: 'ANSI',
      lineNumber: '自动生成',
      specialChars: '有限支持',
    },
    tips: ['与 FANUC 兼容性好', '适用于中小机床', '性价比高', '支持宏程序', '国内使用广泛'],
  },
  {
    id: 'haas',
    name: 'Haas 哈斯',
    country: '美国',
    logo: '🔷',
    features: {
      fullName: 'Haas Automation, Inc.',
      marketShare: '北美领先',
      reliability: '高',
      programmingEase: '简单',
      commonModels: ['VF-2SS', 'VF-6', 'EC-1600'],
    },
    codeDifferences: {
      coordinates: 'G90 绝对 / G91 增量',
      feedRate: 'F100 (mm/min)',
      toolChange: 'M6 T代码',
      spindle: 'S1000 M3',
      coolant: 'M8 开 / M9 关',
    },
    postProcessor: {
      code: 'HAAS_VF',
      fileFormat: '.NC',
      encoding: 'ANSI',
      lineNumber: '自动生成',
      specialChars: '支持',
    },
    tips: ['与 FANUC 代码兼容', '支持高速加工', '适合模具加工', '运行稳定', '全球服务网络'],
  },
  {
    id: 'mitsubishi',
    name: 'Mitsubishi 三菱',
    country: '日本',
    logo: '🔶',
    features: {
      fullName: 'Mitsubishi Electric Corporation',
      marketShare: '亚洲领先',
      reliability: '高',
      programmingEase: '简单',
      commonModels: ['M70V', 'M70A', 'E70'],
    },
    codeDifferences: {
      coordinates: 'G90 绝对 / G91 增量',
      feedRate: 'F100 (mm/min) 或 F0.1 (mm/r)',
      toolChange: 'M6 T代码',
      spindle: 'S1000 M3',
      coolant: 'M8 开 / M9 关',
    },
    postProcessor: {
      code: 'MITSUBISHI_M70',
      fileFormat: '.NC',
      encoding: 'ANSI',
      lineNumber: '自动生成',
      specialChars: '支持',
    },
    tips: ['与 FANUC 代码高度兼容', '支持高速铣削功能', 'M70 系列性能强劲', '适合模具和零件加工', 'PLC 编程灵活'],
  },
  {
    id: 'syntec',
    name: 'Syntec 新代',
    country: '中国台湾',
    logo: '🟣',
    features: {
      fullName: '新代科技股份有限公司',
      marketShare: '台湾领先',
      reliability: '中等',
      programmingEase: '简单',
      commonModels: ['Syntec 10A', 'Syntec 11MA', 'Syntec 220'],
    },
    codeDifferences: {
      coordinates: 'G90 绝对 / G91 增量',
      feedRate: 'F100 (mm/min)',
      toolChange: 'M6 T代码',
      spindle: 'S1000 M3',
      coolant: 'M8 开 / M9 关',
    },
    postProcessor: {
      code: 'SYNTEC_10A',
      fileFormat: '.NC',
      encoding: 'ANSI',
      lineNumber: '自动生成',
      specialChars: '有限支持',
    },
    tips: ['与 FANUC 兼容性好', '价格优势明显', '适用于中小机床', '支持多轴联动', '中文界面友好'],
  },
]

export const codeComparison = [
  {
    feature: '绝对/增量坐标',
    fanuc: 'G90/G91',
    siemens: 'G90/G91',
    heidenhain: 'G90/G91',
    huazhong: 'G90/G91',
    haas: 'G90/G91',
    mitsubishi: 'G90/G91',
    syntec: 'G90/G91',
  },
  {
    feature: '快速定位',
    fanuc: 'G00',
    siemens: 'G00',
    heidenhain: 'G00',
    huazhong: 'G00',
    haas: 'G00',
    mitsubishi: 'G00',
    syntec: 'G00',
  },
  {
    feature: '直线插补',
    fanuc: 'G01',
    siemens: 'G01',
    heidenhain: 'G01',
    huazhong: 'G01',
    haas: 'G01',
    mitsubishi: 'G01',
    syntec: 'G01',
  },
  {
    feature: '圆弧插补',
    fanuc: 'G02/CW G03/CCW',
    siemens: 'G02/CW G03/CCW',
    heidenhain: 'G02/CW G03/CCW',
    huazhong: 'G02/CW G03/CCW',
    haas: 'G02/CW G03/CCW',
    mitsubishi: 'G02/CW G03/CCW',
    syntec: 'G02/CW G03/CCW',
  },
  {
    feature: '刀具半径补偿',
    fanuc: 'G41/G42',
    siemens: 'G41/G42',
    heidenhain: 'G41/G42',
    huazhong: 'G41/G42',
    haas: 'G41/G42',
    mitsubishi: 'G41/G42',
    syntec: 'G41/G42',
  },
  {
    feature: '刀具长度补偿',
    fanuc: 'G43/G44',
    siemens: 'G43/G44',
    heidenhain: 'G43/G44',
    huazhong: 'G43/G44',
    haas: 'G43/G44',
    mitsubishi: 'G43/G44',
    syntec: 'G43/G44',
  },
  {
    feature: '工件坐标系',
    fanuc: 'G54-G59',
    siemens: 'G54-G59',
    heidenhain: 'G54-G59',
    huazhong: 'G54-G59',
    haas: 'G54-G59',
    mitsubishi: 'G54-G59',
    syntec: 'G54-G59',
  },
  {
    feature: '自动换刀',
    fanuc: 'M6 T',
    siemens: 'M6 T',
    heidenhain: 'TOOL CALL',
    huazhong: 'M6 T',
    haas: 'M6 T',
    mitsubishi: 'M6 T',
    syntec: 'M6 T',
  },
  {
    feature: '冷却液',
    fanuc: 'M8/M9',
    siemens: 'M7/M8/M9',
    heidenhain: 'M8/M9',
    huazhong: 'M8/M9',
    haas: 'M8/M9',
    mitsubishi: 'M8/M9',
    syntec: 'M8/M9',
  },
  {
    feature: '子程序',
    fanuc: 'M98 P',
    siemens: 'CALL',
    heidenhain: 'CALL',
    huazhong: 'M98 P',
    haas: 'M98 P',
    mitsubishi: 'M98 P',
    syntec: 'M98 P',
  },
  {
    feature: '程序结束',
    fanuc: 'M30',
    siemens: 'M30',
    heidenhain: 'M30',
    huazhong: 'M30',
    haas: 'M30',
    mitsubishi: 'M30',
    syntec: 'M30',
  },
]

export const postProcessorSelection = [
  { condition: 'FANUC 系统', recommendation: '选择 FANUC_0i 后处理器', notes: '适用于大多数 FANUC 0i 系列机床' },
  { condition: 'Siemens 系统', recommendation: '选择 SIEMENS_840D 后处理器', notes: '适用于 840D/828D 系列' },
  { condition: 'Heidenhain 系统', recommendation: '选择 HEIDENHAIN_TNC640 后处理器', notes: '对话式编程，格式稍有不同' },
  { condition: '华中/凯恩帝系统', recommendation: '选择 HUAZHONG/KND 后处理器', notes: '与 FANUC 兼容性好' },
  { condition: 'Haas 系统', recommendation: '选择 HAAS_VF 后处理器', notes: '适用于 VF/EC 系列' },
  { condition: 'Mitsubishi 系统', recommendation: '选择 MITSUBISHI_M70 后处理器', notes: '适用于 M70V/M70A/E70 系列' },
  { condition: 'Syntec 系统', recommendation: '选择 SYNTEC_10A 后处理器', notes: '适用于 10A/11MA/220 系列' },
]
