export const materials = [
  {
    code: '45#',
    name: '45号钢',
    category: '碳素结构钢',
    density: 7.85,
    hardness: 'HB217-255',
    tensileStrength: 600,
    yieldStrength: 355,
    elongation: 16,
    thermalConductivity: 49.8,
    machinability: '易加工',
    machinabilityLevel: 2,
    applications: '主轴、齿轮、轴类零件、模具、夹具',
    notes: '综合力学性能好，调质处理后可获得良好的韧性和强度',
  },
  {
    code: '40Cr',
    name: '40铬钢',
    category: '合金结构钢',
    density: 7.85,
    hardness: 'HB207-228',
    tensileStrength: 980,
    yieldStrength: 785,
    elongation: 9,
    thermalConductivity: 46.1,
    machinability: '中等',
    machinabilityLevel: 3,
    applications: '传动轴、齿轮、连杆、高强度螺栓',
    notes: '调质处理后具有优良的综合力学性能，广泛用于中等载荷零件',
  },
  {
    code: '304',
    name: '304不锈钢',
    category: '奥氏体不锈钢',
    density: 7.93,
    hardness: 'HB≤187',
    tensileStrength: 520,
    yieldStrength: 205,
    elongation: 40,
    thermalConductivity: 16.2,
    machinability: '难加工',
    machinabilityLevel: 5,
    applications: '化工设备、食品机械、装饰管材、压力容器',
    notes: '耐腐蚀性优异，切削时易产生积屑瘤，需使用锋利刀具',
  },
  {
    code: '316L',
    name: '316L不锈钢',
    category: '奥氏体不锈钢',
    density: 7.98,
    hardness: 'HB≤217',
    tensileStrength: 480,
    yieldStrength: 170,
    elongation: 45,
    thermalConductivity: 15.9,
    machinability: '难加工',
    machinabilityLevel: 5,
    applications: '医疗植入物、制药设备、海洋设备',
    notes: '低碳含量，焊接性好，耐腐蚀性优于304',
  },
  {
    code: '6061',
    name: '6061铝合金',
    category: '变形铝合金',
    density: 2.7,
    hardness: 'HB95(T6)',
    tensileStrength: 310,
    yieldStrength: 276,
    elongation: 12,
    thermalConductivity: 167,
    machinability: '易加工',
    machinabilityLevel: 1,
    applications: '结构件、框架、散热器、外壳',
    notes: '切削性能优良，导热性好，适用于高速切削',
  },
  {
    code: '7075',
    name: '7075铝合金',
    category: '超硬铝合金',
    density: 2.81,
    hardness: 'HB150(T6)',
    tensileStrength: 572,
    yieldStrength: 503,
    elongation: 11,
    thermalConductivity: 130,
    machinability: '中等',
    machinabilityLevel: 3,
    applications: '航空结构件、高强度零件、模具',
    notes: '强度高，切削时需注意切削力和变形',
  },
  {
    code: '65Mn',
    name: '65锰钢',
    category: '弹簧钢',
    density: 7.81,
    hardness: 'HB≤285',
    tensileStrength: 980,
    yieldStrength: 785,
    elongation: 12,
    thermalConductivity: 40.2,
    machinability: '中等',
    machinabilityLevel: 4,
    applications: '弹簧、弹簧垫圈、离合器片',
    notes: '淬火回火后具有良好的弹性和耐磨性',
  },
  {
    code: 'HT200',
    name: 'HT200灰铸铁',
    category: '铸铁',
    density: 7.2,
    hardness: 'HB170-220',
    tensileStrength: 200,
    yieldStrength: 120,
    elongation: 1,
    thermalConductivity: 47,
    machinability: '易加工',
    machinabilityLevel: 1,
    applications: '箱体、导轨、机座、轴承座',
    notes: '减震性好，切削性能优良，耐磨性好',
  },
  {
    code: 'QT600',
    name: 'QT600球墨铸铁',
    category: '球墨铸铁',
    density: 7.1,
    hardness: 'HB229-302',
    tensileStrength: 600,
    yieldStrength: 370,
    elongation: 3,
    thermalConductivity: 32,
    machinability: '中等',
    machinabilityLevel: 3,
    applications: '曲轴、齿轮、连杆、缸体',
    notes: '强度接近钢，切削性能好，耐磨性好',
  },
  {
    code: 'T1紫铜',
    name: 'T1紫铜',
    category: '纯铜',
    density: 8.96,
    hardness: 'HB60-70',
    tensileStrength: 200,
    yieldStrength: 60,
    elongation: 45,
    thermalConductivity: 401,
    machinability: '易加工',
    machinabilityLevel: 2,
    applications: '导电材料、散热器、热交换器',
    notes: '导电性和导热性优异，切削时易粘刀',
  },
  {
    code: 'H62黄铜',
    name: 'H62黄铜',
    category: '黄铜',
    density: 8.5,
    hardness: 'HB≥85',
    tensileStrength: 370,
    yieldStrength: 150,
    elongation: 20,
    thermalConductivity: 121,
    machinability: '易加工',
    machinabilityLevel: 1,
    applications: '阀门、管件、装饰件、轴承',
    notes: '切削性能优良，耐腐蚀，广泛应用于五金件',
  },
  {
    code: 'TC4钛合金',
    name: 'TC4钛合金',
    category: '钛合金',
    density: 4.51,
    hardness: 'HB≤235',
    tensileStrength: 895,
    yieldStrength: 820,
    elongation: 10,
    thermalConductivity: 7.2,
    machinability: '难加工',
    machinabilityLevel: 5,
    applications: '航空构件、医疗植入物、化工设备',
    notes: '强度重量比高，导热性差，切削需低速度大进给',
  },
]

export const machinabilityLevels = [
  { level: 1, label: '易加工', color: '#10b981', desc: '切削性能优良，刀具寿命长，表面质量好' },
  { level: 2, label: '较易加工', color: '#22c55e', desc: '切削性能良好，需选用合适刀具参数' },
  { level: 3, label: '中等加工', color: '#f59e0b', desc: '切削性能一般，需控制切削参数' },
  { level: 4, label: '较难加工', color: '#f97316', desc: '切削性能较差，需优化工艺参数' },
  { level: 5, label: '难加工', color: '#ef4444', desc: '切削性能差，需专用刀具和工艺' },
]

export const materialCategories = ['碳素结构钢', '合金结构钢', '奥氏体不锈钢', '变形铝合金', '超硬铝合金', '弹簧钢', '铸铁', '球墨铸铁', '纯铜', '黄铜', '钛合金']
