export const processCards = [
  {
    key: 'shaft',
    title: '轴类零件',
    icon: '⚙️',
    description: '典型阶梯轴加工工艺卡，涵盖下料→车削→铣键槽→热处理→精加工全流程',
    material: '45# / 40Cr / 304',
    hardness: 'HB 200-250 / HRC 40-50',
    tolerance: 'IT7-IT9',
    roughness: 'Ra 1.6-6.3',
    processes: [
      {
        seq: 1,
        stage: '下料',
        operation: '下料',
        machine: '带锯床',
        tool: '带锯条',
        params: '锯切速度 30-50 m/min，进给 0.5-1.5 mm/齿',
        time: '5 min',
        note: '毛坯留 3-5 mm 加工余量',
      },
      {
        seq: 2,
        stage: '粗加工',
        operation: '车外圆、端面',
        machine: '数控车床',
        tool: '硬质合金外圆车刀 (CNMG)',
        params: 'vc=120 m/min, f=0.3 mm/r, ap=2-4 mm',
        time: '15 min',
        note: '留 1-2 mm 精加工余量',
      },
      {
        seq: 3,
        stage: '粗加工',
        operation: '钻中心孔、钻孔',
        machine: '数控车床',
        tool: '中心钻 / 高速钢钻头',
        params: 'vc=80-100 m/min, f=0.1 mm/r',
        time: '3 min',
        note: '中心孔 A 型或 B 型',
      },
      {
        seq: 4,
        stage: '半精加工',
        operation: '车阶梯外圆、圆锥面',
        machine: '数控车床',
        tool: '涂层硬质合金车刀',
        params: 'vc=150-180 m/min, f=0.15-0.2 mm/r, ap=0.5-1 mm',
        time: '10 min',
        note: '保证轴肩尺寸精度',
      },
      {
        seq: 5,
        stage: '半精加工',
        operation: '铣键槽',
        machine: '立式加工中心',
        tool: '键槽铣刀 / 三面刃铣刀',
        params: 'vc=100-120 m/min, f=0.1-0.15 mm/z, ap=槽深',
        time: '8 min',
        note: '键槽宽度公差 H8',
      },
      {
        seq: 6,
        stage: '热处理',
        operation: '调质 / 淬火',
        machine: '热处理炉',
        tool: '—',
        params: '调质: 840°C 淬火 + 600°C 回火；淬火: 820-860°C',
        time: '2 h',
        note: '按硬度要求选择工艺',
      },
      {
        seq: 7,
        stage: '精加工',
        operation: '磨削外圆',
        machine: '外圆磨床',
        tool: '砂轮 WA60#',
        params: 'vc=30-50 m/s, f=0.5-1 mm/r, ap=0.005-0.02 mm',
        time: '20 min',
        note: '达到 Ra 0.4-0.8，IT7 精度',
      },
      {
        seq: 8,
        stage: '精加工',
        operation: '铣键槽 / 磨键槽',
        machine: '立式加工中心 / 工具磨床',
        tool: '硬质合金铣刀 / 成形砂轮',
        params: '精铣 f=0.05 mm/z, ap=0.2 mm',
        time: '5 min',
        note: '保证槽宽与对称性',
      },
      {
        seq: 9,
        stage: '检验',
        operation: '尺寸检验、形位公差',
        machine: '三坐标测量仪',
        tool: '测头 / 千分表',
        params: '按图纸全尺寸检测',
        time: '10 min',
        note: '首件全检，过程抽检',
      },
    ],
  },
  {
    key: 'plate',
    title: '盘类零件',
    icon: '🔘',
    description: '典型端盖/法兰盘加工工艺卡，含车削端面、铣平面、钻孔、攻牙等工序',
    material: 'HT200 / 45# / 6061-T6',
    hardness: 'HB 150-200',
    tolerance: 'IT7-IT10',
    roughness: 'Ra 1.6-3.2',
    processes: [
      {
        seq: 1,
        stage: '下料',
        operation: '下料',
        machine: '带锯床 / 车床切断',
        tool: '带锯条 / 切断刀',
        params: '留 3-4 mm 余量',
        time: '5 min',
        note: '圆钢下料，端面留余量',
      },
      {
        seq: 2,
        stage: '粗加工',
        operation: '车外圆、端面',
        machine: '数控车床',
        tool: '硬质合金车刀 (CNMG)',
        params: 'vc=120-150 m/min, f=0.3 mm/r, ap=3-5 mm',
        time: '12 min',
        note: '车到接近成品尺寸，留 1 mm 余量',
      },
      {
        seq: 3,
        stage: '粗加工',
        operation: '铣端面、平面',
        machine: '立式加工中心',
        tool: '面铣刀 / 立铣刀',
        params: 'vc=200-300 m/min, f=0.1-0.2 mm/z, ap=1-2 mm',
        time: '10 min',
        note: '保证平行度和平面度',
      },
      {
        seq: 4,
        stage: '半精加工',
        operation: '钻孔、锪孔',
        machine: '立式加工中心',
        tool: '硬质合金钻头 / 锪钻',
        params: 'vc=80-120 m/min, f=0.08-0.12 mm/r',
        time: '8 min',
        note: '孔位精度 ±0.05 mm',
      },
      {
        seq: 5,
        stage: '半精加工',
        operation: '攻牙',
        machine: '立式加工中心',
        tool: '丝锥 (M6-M12)',
        params: 'vc=10-20 m/min, 同步攻牙',
        time: '6 min',
        note: '底孔 = 公称直径 - 1.08P',
      },
      {
        seq: 6,
        stage: '精加工',
        operation: '精铣平面、台阶',
        machine: '立式加工中心',
        tool: '硬质合金精铣刀',
        params: 'vc=300-500 m/min, f=0.05-0.1 mm/z, ap=0.2-0.5 mm',
        time: '8 min',
        note: 'Ra 1.6 以上',
      },
      {
        seq: 7,
        stage: '精加工',
        operation: '车内孔、精车端面',
        machine: '数控车床',
        tool: '内孔镗刀 / 精车刀',
        params: 'vc=150-200 m/min, f=0.1 mm/r, ap=0.1-0.3 mm',
        time: '10 min',
        note: '内孔 H7 配合精度',
      },
      {
        seq: 8,
        stage: '检验',
        operation: '全尺寸检验',
        machine: '三坐标 / 投影仪',
        tool: '测头 / 量具',
        params: '重点检测孔径、孔距',
        time: '8 min',
        note: '首件全检',
      },
    ],
  },
  {
    key: 'box',
    title: '箱体类零件',
    icon: '📦',
    description: '典型箱体/基座加工工艺卡，含粗铣、精铣、钻孔、镗孔等复杂工序',
    material: 'HT250 / QT600 / 45#',
    hardness: 'HB 180-230',
    tolerance: 'IT7-IT9',
    roughness: 'Ra 1.6-6.3',
    processes: [
      {
        seq: 1,
        stage: '下料',
        operation: '下料',
        machine: '带锯床',
        tool: '带锯条',
        params: '各面留 3-5 mm 余量',
        time: '10 min',
        note: '铸件毛坯或钢件下料',
      },
      {
        seq: 2,
        stage: '粗加工',
        operation: '粗铣六面',
        machine: '立式加工中心',
        tool: '大直径面铣刀',
        params: 'vc=150-200 m/min, f=0.2-0.3 mm/z, ap=2-4 mm',
        time: '25 min',
        note: '保证基准面，留 1 mm 余量',
      },
      {
        seq: 3,
        stage: '粗加工',
        operation: '粗铣内腔、槽',
        machine: '立式加工中心',
        tool: '圆角铣刀 / 型腔铣',
        params: 'vc=120-180 m/min, f=0.15-0.2 mm/z, ap=1-3 mm',
        time: '40 min',
        note: '型腔铣 UG 策略',
      },
      {
        seq: 4,
        stage: '半精加工',
        operation: '钻孔、扩孔',
        machine: '立式加工中心',
        tool: '硬质合金钻头',
        params: 'vc=80-120 m/min, f=0.08-0.15 mm/r',
        time: '15 min',
        note: '孔位精度 ±0.05 mm',
      },
      {
        seq: 5,
        stage: '半精加工',
        operation: '镗孔',
        machine: '卧式加工中心 / 镗床',
        tool: '镗刀杆 / 微调镗刀',
        params: 'vc=80-100 m/min, f=0.05-0.1 mm/r, ap=0.1-0.3 mm',
        time: '20 min',
        note: '保证孔的圆度与直线度',
      },
      {
        seq: 6,
        stage: '精加工',
        operation: '精铣各面、内腔',
        machine: '立式加工中心',
        tool: '硬质合金精铣刀',
        params: 'vc=300-400 m/min, f=0.05-0.1 mm/z, ap=0.2-0.5 mm',
        time: '30 min',
        note: 'Ra 1.6-3.2',
      },
      {
        seq: 7,
        stage: '精加工',
        operation: '精镗孔到尺寸',
        machine: '卧式加工中心 / 磨床',
        tool: '精镗刀 / 内圆磨',
        params: '精镗 f=0.05 mm/r, 磨削 ap=0.005 mm',
        time: '15 min',
        note: '达到 H7 配合精度',
      },
      {
        seq: 8,
        stage: '检验',
        operation: '全尺寸检验',
        machine: '三坐标测量仪',
        tool: '测头',
        params: '重点: 孔距、同轴度、平面度',
        time: '20 min',
        note: '首件全检 + 过程巡检',
      },
    ],
  },
  {
    key: 'gear',
    title: '齿轮类零件',
    icon: '🔱',
    description: '典型圆柱齿轮加工工艺卡，含滚齿、插齿、铣齿、磨齿等核心工序',
    material: '45# / 40Cr / 20CrMnTi',
    hardness: 'HB 200-300 / HRC 56-62',
    tolerance: 'IT6-IT8 (齿轮精度 7-8 级)',
    roughness: 'Ra 0.4-1.6',
    processes: [
      {
        seq: 1,
        stage: '下料',
        operation: '下料',
        machine: '带锯床 / 车床',
        tool: '带锯条 / 切断刀',
        params: '留 3-5 mm 余量',
        time: '5 min',
        note: '圆钢下料',
      },
      {
        seq: 2,
        stage: '粗加工',
        operation: '车外圆、端面、钻孔',
        machine: '数控车床',
        tool: '硬质合金车刀 / 钻头',
        params: 'vc=120-150 m/min, f=0.3 mm/r',
        time: '15 min',
        note: '车到齿根圆以下 0.5 mm',
      },
      {
        seq: 3,
        stage: '半精加工',
        operation: '滚齿 / 插齿',
        machine: '滚齿机 / 插齿机',
        tool: '滚刀 / 插齿刀',
        params: 'vc=30-50 m/min, f=0.1-0.2 mm/r, 留 0.1-0.2 mm 磨量',
        time: '30 min',
        note: '按模数选刀具，滚齿精度 7 级',
      },
      {
        seq: 4,
        stage: '热处理',
        operation: '渗碳淬火 / 高频淬火',
        machine: '热处理炉',
        tool: '—',
        params: '渗碳 0.6-1.0 mm 深, 淬火 HRC 58-62',
        time: '4 h',
        note: '控制渗碳层深度和硬度',
      },
      {
        seq: 5,
        stage: '精加工',
        operation: '磨齿',
        machine: '成型磨齿机 / 展成磨齿机',
        tool: '成型砂轮',
        params: 'vc=20-30 m/s, f=0.01-0.02 mm/r, ap=0.005-0.02 mm',
        time: '25 min',
        note: '达到 6-7 级精度，Ra 0.4-0.8',
      },
      {
        seq: 6,
        stage: '精加工',
        operation: '车削/磨削基准面',
        machine: '数控车床 / 外圆磨床',
        tool: '精车刀 / 砂轮',
        params: '精车 f=0.05 mm/r, 磨削 ap=0.005 mm',
        time: '10 min',
        note: '保证端面与轴线垂直度',
      },
      {
        seq: 7,
        stage: '检验',
        operation: '齿形检验、尺寸检验',
        machine: '齿轮测量中心 / 三坐标',
        tool: '齿轮测头',
        params: '检测齿距累积误差、齿形误差',
        time: '15 min',
        note: '首件全检齿形',
      },
    ],
  },
]
